//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OfficeTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tb_Product()
        {
            this.Tb_ProductReceive = new HashSet<Tb_ProductReceive>();
            this.Tb_ProductStore = new HashSet<Tb_ProductStore>();
        }
    
        public int Product_Id { get; set; }
        public string Product_Name { get; set; }
        public int Product_Price { get; set; }
        public string Product_Description { get; set; }
        public int Brand_Id { get; set; }
        public Nullable<int> Unit_Id { get; set; }
    
        public virtual Tb_Brand Tb_Brand { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_ProductReceive> Tb_ProductReceive { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_ProductStore> Tb_ProductStore { get; set; }
        public virtual Tb_Unit Tb_Unit { get; set; }
    }
}
