//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OfficeTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_ProductStore
    {
        public int ProductStore_Id { get; set; }
        public Nullable<int> Product_Id { get; set; }
        public Nullable<int> Balance_Qty { get; set; }
    
        public virtual Tb_Product Tb_Product { get; set; }
    }
}
